# serverless.yml

# The service name
service: expence-manager-nuxt-serverless

# provider information
# we are deploying on aws using the node 10.x runtime.
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
functions:
  app:
    handler: lambda.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

# Add those plugins to our service
plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-domain-manager
#  - serverless-dotenv-plugin
custom:
  apigwBinary:
    types:
      - '*/*'
  # カスタムドメインの設定
  # TODO ステージごとにドメイン切り替え
  customDomain:
    domainName: expense-manager.cloud
    certificateName: 'expense-manager.cloud'
    basePath: ''
    stage: prod
    createRoute53Record: true
  serverless-offline:
    httpPort: 8000
    lambdaPort: 8001
